### ISSUE TITLE
Missing SOPs and Voices release 1.1 [Closed]

### ISSUE THREAD

**Issue by Ulazygit** [patrickl92/AudioChecklist#1]
No voices or SOP selectable. No instruction in manual on where to download voices and SOP
![bug](https://user-images.githubusercontent.com/60723284/150118468-6d2f9b67-d641-42de-bb60-02e76ab31271.JPG)

Also please add option to silence PF.

**Comment by patrickl92** [comment]
I'll add the link to the SOPs to the manual. For the other request: It is not possible to silence a the PF, because I can't set the volume to zero. This is not allowed by X-Plane, I can only set it to a very low volume. What would be possible is that you can also select "Silent" as PF, which would basically do not activate a PF at all.
However, this brings up another question: What should be the time to wait before going to the next checklist item? It usually does so if the PF finished speaking, but with this option you wouldn't have a PF. I could put in a delay for 1 second, for example.

**Comment by Ulazygit** [comment]
I have found an easy solution. One has to simply delete the appropriate pilot flying audio files and this doesn't break the script. I then just increased the delay as you suggested and it works nicely. I have a button that I use to skip to the next challenge if my readback is faster. 

P.S. Superb addon.

**Comment by patrickl92** [comment]
Thank you. I will close that now.
