### ISSUE TITLE
Lua exits with an error when using the checklists for an unsupported plane

### ISSUE THREAD

**Issue by Ulazygit** [patrickl92/AudioChecklist#12]
Firstly, thank you for implementing the manual mode. It's taken my simming to the next level!

Would it be possible to run checklists for a different aircraft different to the one I am flying when in manual.mode. I.e. use the Zibo checklist in manual mode for the ixeg 737?

**Comment by patrickl92** [comment]
You can run any checklists on any aircraft. Have you tried it? It should work.

**Comment by Ulazygit** [comment]
yes but it eventually crashes the script saying attempted to compare nil
with number and then i have to reload the lua to start it again. This is
when using fjs732 with 738 checklist

**Comment by patrickl92** [comment]
Can you attach the X-Plane log file to the GitHub issue after you have triggered that error? I'll have a look.

**Comment by Ulazygit** [comment]
[Log.txt](https://github.com/patrickl92/AudioChecklist/files/8119855/Log.txt)
![error](https://user-images.githubusercontent.com/60723284/155211403-1826fdb3-40d3-41aa-9aa3-5a174c354b2e.JPG)

**Comment by patrickl92** [comment]
I have changed the title, because it was actually a bug. It shouldn't cause an error when using the checklists for an unsupported plane. I have fixed that and released a new version of the AudioChecklist core and the SOPs. You need to update both the AudioChecklist core and the Zibo SOP.
Please let me know if it works with the new releases.

**Comment by patrickl92** [comment]
@Ulazygit Have you tried the new release yet?

**Comment by patrickl92** [comment]
Closed due to inactivity
