### ISSUE TITLE
[Feature Request] Option to manually check every item.

### ISSUE THREAD

**Issue by Ulazygit** [patrickl92/AudioChecklist#8]
As mentioned in my last post, I deleted the pilot flying response audio files, and tweaked the delays to make it more realistic in that I respond to the checklist challenges myself instead of being in the jumpseat listening to two guys playing CRM tennis.

To enhance this, would it be possible to **add an option where items are not auto-completed, and instead, the skip button is required to progress to the next item** (as it currently does for some items such as briefing). Because I deleted the audio files, the next challenge sometimes comes too fast or too slow for my liking. 

I am really enjoying this plugin as it makes me feel like I have a real PM with me. The fact that you didn't opt for cheesy TTS voices makes this all the better.

**Comment by patrickl92** [comment]
Would you then also check all the items yourself? I'm thinking of some kind of "manual mode", which basically turns all checklist items into manual ones. With this option enabled, no checks would be performed and all items would get the green "Done" button to continue the checklist. This option would also allow me to easily ignore the responses, which means you would'nt need to delete any files and therefore you can update to newer releases without any issues.

**Comment by Ulazygit** [comment]
Absolutely. Sorry thought I had already responded to this

**Comment by hugoghx** [comment]
+1 on this.

Under `3. Select Pilots`, I'd love to have a `You` (or `Me`, `Myself`, etc) option for both the PM and PF, meaning I'd be either responsible for challenging (if PM) or replying to the challenge (if PF).

--- 

As mentioned before a workaround for now is to delete the files in the `responses`  folder of some voice you don't want to use, or:

1. Under `voices`, create folder named `You` with an empty `responses` folder inside.

2. Then add this line of code:
```lua
local voiceYou = waveFileVoice:new("You", nil, voicesDirectory .. "You" .. DIRECTORY_SEPARATOR .. "responses")
```
[In this line](https://github.com/patrickl92/AudioChecklistSOPs/blob/main/SOP/B737_ZiboDefault/Scripts/AudioChecklist_B737_ZiboDefault.lua#L40) (I'm using the Zibo SOP, choose your file accordingly if you're not).

3. And this line of code:
```lua
ziboDefaultSOP:addResponseVoice(voiceYou)
```

[In this line](https://github.com/patrickl92/AudioChecklistSOPs/blob/main/SOP/B737_ZiboDefault/Scripts/AudioChecklist_B737_ZiboDefault.lua#L49) (Again, using Zibo SOP, choose your file accordingly if you're not).


Now you can choose `You` in the PF menu and it'll be a silent actor. You'll still need to tweak the response delays to fit your ability to reply to the checklist - and this is where an actual feature instead of this workaround starts to be useful!

**Comment by patrickl92** [comment]
@hugoamvieira For the responses, that would be quite easy I guess. It would work as I described above: You would need to check each item by yourself and then click a button or use a key/joystick binding to continue to the next item.

Having an empty voice for the challenges is a bit more tricky, because there is no trigger when to play the response of the current item after the previous item has been completed. The empty voice can simulate a duration which then acts as a delay, but selecting the correct delay is the hard part here. It shouldn't be too long and neither too short.

**Comment by hugoghx** [comment]
Yeah, I think making the player essentially do the PM role here would be tough since different people would narrate different checklist challenges at different speeds, so it's a hard one that a static delay (even at a per-checklist-item level) wouldn't effectively solve. 

We'd probably need some sort of delay that is a function of:
1. How big the challenge sentence is (as narrated by an average person) and, 
2. A delay modifier to speed up/slow down that "base delay", based on user preference;

But even then I'm sure this wouldn't be configurable enough for some people.

---

Thankfully, the PF side of things is easier (relatively) - We could start there.

**Comment by charles-vomacka** [comment]
I second this request. Would be nice if I could visually check and then when confirming compliance click a button which triggers the voice response and the next checklist item voice challenge.

**Comment by patrickl92** [comment]
I have implemented the requested changes. Before acutally releasing it, I ask you all to take a look at this preview. Just update the files as you would do with a normal release (that is, copy the content again and replace all the existing files).

[AudioChecklist_1.2.0-rc.1.zip](https://github.com/patrickl92/AudioChecklist/files/8044318/AudioChecklist_1.2.0-rc.1.zip)

Changes:
* The preferences window contains a new option to set the execution mode. If you hover over an execution mode with the mouse, you will get a tooltip which explains how that mode works. Can be changed anytime, even if a checklist is currently executed
* A new voice named "Me" can be selected as the PF. When selected, no responses are played. This only makes sense with the execution mode "Manual", but I don't prevent using it with any other execution mode

Looking forward to your feedback

**Comment by charles-vomacka** [comment]
I have tried it and it works great. Will let you know if I notice any issues.

Thanks for this great plugin, and thanks for implementing these changes - especially so quickly.

**Comment by hugoghx** [comment]
+1 here. Been trying it out in manual mode and auto mode and it's working like a charm.

What a great change! 🥇

**Comment by patrickl92** [comment]
Since you found no issues, I will release the changes. Thank you for testing it.
